version: '3.8'
services:
# store node info
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - cloud-edge-net
    volumes:
      - mongodb-data:/data/db

# di
  resource-discovery:
    build:
      context: ./docker/resource-discovery
      dockerfile: Dockerfile
    container_name: resource-discovery
    networks:
      - cloud-edge-net
    depends_on:
      - mongodb

networks:
  cloud-edge-net:
    name: cloud-edge-net
    driver: bridge

# volumes:
#   mongodb-data:
