// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: comm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeID    string                 `protobuf:"bytes,1,opt,name=fromNodeID,proto3" json:"fromNodeID,omitempty"`
	ToNodeID      string                 `protobuf:"bytes,2,opt,name=toNodeID,proto3" json:"toNodeID,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // nanoseconds since epoch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetFromNodeID() string {
	if x != nil {
		return x.FromNodeID
	}
	return ""
}

func (x *PingRequest) GetToNodeID() string {
	if x != nil {
		return x.ToNodeID
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeID    string                 `protobuf:"bytes,1,opt,name=fromNodeID,proto3" json:"fromNodeID,omitempty"`
	ToNodeID      string                 `protobuf:"bytes,2,opt,name=toNodeID,proto3" json:"toNodeID,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`         // original ping timestamp
	PongTimestamp int64                  `protobuf:"varint,4,opt,name=pongTimestamp,proto3" json:"pongTimestamp,omitempty"` // time at responder when sending pong
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetFromNodeID() string {
	if x != nil {
		return x.FromNodeID
	}
	return ""
}

func (x *PongResponse) GetToNodeID() string {
	if x != nil {
		return x.ToNodeID
	}
	return ""
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PongResponse) GetPongTimestamp() int64 {
	if x != nil {
		return x.PongTimestamp
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{2}
}

type RTTMatrixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Entries       []*RTTEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTTMatrixResponse) Reset() {
	*x = RTTMatrixResponse{}
	mi := &file_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTTMatrixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTMatrixResponse) ProtoMessage() {}

func (x *RTTMatrixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTMatrixResponse.ProtoReflect.Descriptor instead.
func (*RTTMatrixResponse) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{3}
}

func (x *RTTMatrixResponse) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RTTMatrixResponse) GetEntries() []*RTTEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RTTEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeID    string                 `protobuf:"bytes,1,opt,name=fromNodeID,proto3" json:"fromNodeID,omitempty"`
	ToNodeID      string                 `protobuf:"bytes,2,opt,name=toNodeID,proto3" json:"toNodeID,omitempty"`
	Rtt           int64                  `protobuf:"varint,3,opt,name=rtt,proto3" json:"rtt,omitempty"` // nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTTEntry) Reset() {
	*x = RTTEntry{}
	mi := &file_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTTEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTEntry) ProtoMessage() {}

func (x *RTTEntry) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTEntry.ProtoReflect.Descriptor instead.
func (*RTTEntry) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{4}
}

func (x *RTTEntry) GetFromNodeID() string {
	if x != nil {
		return x.FromNodeID
	}
	return ""
}

func (x *RTTEntry) GetToNodeID() string {
	if x != nil {
		return x.ToNodeID
	}
	return ""
}

func (x *RTTEntry) GetRtt() int64 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

var File_comm_proto protoreflect.FileDescriptor

const file_comm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"comm.proto\x12\x05proto\"g\n" +
	"\vPingRequest\x12\x1e\n" +
	"\n" +
	"fromNodeID\x18\x01 \x01(\tR\n" +
	"fromNodeID\x12\x1a\n" +
	"\btoNodeID\x18\x02 \x01(\tR\btoNodeID\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x8e\x01\n" +
	"\fPongResponse\x12\x1e\n" +
	"\n" +
	"fromNodeID\x18\x01 \x01(\tR\n" +
	"fromNodeID\x12\x1a\n" +
	"\btoNodeID\x18\x02 \x01(\tR\btoNodeID\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12$\n" +
	"\rpongTimestamp\x18\x04 \x01(\x03R\rpongTimestamp\"\a\n" +
	"\x05Empty\"T\n" +
	"\x11RTTMatrixResponse\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\x12)\n" +
	"\aentries\x18\x02 \x03(\v2\x0f.proto.RTTEntryR\aentries\"X\n" +
	"\bRTTEntry\x12\x1e\n" +
	"\n" +
	"fromNodeID\x18\x01 \x01(\tR\n" +
	"fromNodeID\x12\x1a\n" +
	"\btoNodeID\x18\x02 \x01(\tR\btoNodeID\x12\x10\n" +
	"\x03rtt\x18\x03 \x01(\x03R\x03rtt2w\n" +
	"\fAgentService\x12/\n" +
	"\x04Ping\x12\x12.proto.PingRequest\x1a\x13.proto.PongResponse\x126\n" +
	"\fGetRTTMatrix\x12\f.proto.Empty\x1a\x18.proto.RTTMatrixResponseB\x1eZ\x1ccloud-edge-agent/proto;protob\x06proto3"

var (
	file_comm_proto_rawDescOnce sync.Once
	file_comm_proto_rawDescData []byte
)

func file_comm_proto_rawDescGZIP() []byte {
	file_comm_proto_rawDescOnce.Do(func() {
		file_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comm_proto_rawDesc), len(file_comm_proto_rawDesc)))
	})
	return file_comm_proto_rawDescData
}

var file_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_comm_proto_goTypes = []any{
	(*PingRequest)(nil),       // 0: proto.PingRequest
	(*PongResponse)(nil),      // 1: proto.PongResponse
	(*Empty)(nil),             // 2: proto.Empty
	(*RTTMatrixResponse)(nil), // 3: proto.RTTMatrixResponse
	(*RTTEntry)(nil),          // 4: proto.RTTEntry
}
var file_comm_proto_depIdxs = []int32{
	4, // 0: proto.RTTMatrixResponse.entries:type_name -> proto.RTTEntry
	0, // 1: proto.AgentService.Ping:input_type -> proto.PingRequest
	2, // 2: proto.AgentService.GetRTTMatrix:input_type -> proto.Empty
	1, // 3: proto.AgentService.Ping:output_type -> proto.PongResponse
	3, // 4: proto.AgentService.GetRTTMatrix:output_type -> proto.RTTMatrixResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_comm_proto_init() }
func file_comm_proto_init() {
	if File_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comm_proto_rawDesc), len(file_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comm_proto_goTypes,
		DependencyIndexes: file_comm_proto_depIdxs,
		MessageInfos:      file_comm_proto_msgTypes,
	}.Build()
	File_comm_proto = out.File
	file_comm_proto_goTypes = nil
	file_comm_proto_depIdxs = nil
}
